events {
}

http {
    server_tokens off;

    client_max_body_size 50M;
    
    gzip on;
    gzip_types application/json;
    
    server {
        listen 80;
        server_name ocr.vladislavzainullin.com;

        return 301 https://$host$request_uri;
    }
    
    server {
        listen 443 ssl;
        
        server_name ocr.vladislavzainullin.com;

        http2 on;
        include conf.d/ssl.conf;
        
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        location / {
            proxy_pass http://host.docker.internal:7207;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port server_port;
        }
    }
}