server {
    listen 80;
    server_name ocr.vladislavzainullin.com;

    return 301 https://$host$request_uri;
}
    
server {
    listen 443 ssl;   
    server_name ocr.vladislavzainullin.com;
    
    include /etc/nginx/snippets/ssl.conf;
    
    proxy_request_buffering off;
        
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    location / {
        proxy_pass http://ocr:7207;

        include /etc/nginx/snippets/proxy.conf
    }
}